theme: jekyll-theme-slate
title: Microsoft Power Platform In a Day Workshop
description: One-day training workshop using Microsoft Power Platform 
relative_links:
  enabled: true
  collections: true
include:
  - README.md
